"""Offline arena win-rate selection primitives."""

from .grade import (
    MemberSlotState,
    MemberSlotMetrics,
    stage_member_cap,
    classify_member_slot,
    fixed_member_slot_boxes,
    team_stage_total_anchors,
)
from .config import ArenaRuntimeConfig
from .reader import (
    TeamTarget,
    ArenaPageState,
    ArenaReaderError,
    ClickedSkillCard,
    ArenaLineupReader,
    MemberObservation,
    ArenaReaderBackend,
    SkillCardSlotState,
    MemberObservationScope,
    classify_arena_page,
    arena_page_allows_team_entry,
    validate_conservative_cost_fallback,
)
from .schema import SnapshotValidationError, validate_snapshot, validate_own_snapshot
from .stages import (
    StageCatalogError,
    ContestStageCatalog,
    ContestStageDefinition,
    ContestSeasonDefinition,
)
from .adapter import AdapterError, OwnScoreBatch, SubprocessArenaAdapter
from .catalog import (
    ArenaCatalogError,
    ArenaEntityCatalog,
    CustomizationObservation,
    CustomizationEvidenceInventoryEntry,
)
from .service import (
    ArenaEvaluation,
    ArenaWinRateService,
    ArenaOwnScoreService,
    ArenaOwnScoreEvaluation,
    prepare_own_score_cache,
    reset_prepared_own_score_cache,
    own_score_cache_prepared_for_current_task,
)
from .decision import ArenaDecision, StageEstimate, OpponentEstimate, select_first_qualified
from .geometry import (
    P_ITEM_SCREEN_SLOT_TO_ENGINE_SLOT,
    canonical_skill_card_rows,
    infer_parameter_label_boxes,
    excluded_duplicate_card_flags,
    p_item_screen_slot_to_engine_slot,
    p_item_screen_order_to_engine_order,
    stable_excluded_duplicate_card_flags,
    resolve_excluded_duplicate_card_flags,
    expected_scrolled_secondary_skill_card_row,
    canonical_scrolled_secondary_skill_card_row,
)
from .card_cost import (
    GenericCostPrediction,
    GenericCostReferenceError,
    GenericCostReferenceGallery,
    stable_generic_cost_value,
)
from .own_cache import (
    DEFAULT_OWN_SCORE_CACHE,
    DEFAULT_OWN_SCORE_SUMMARY,
    OwnScoreCacheError,
    OwnScoreCacheStore,
    OwnScoreResimulationRequired,
)
from .badge_workers import (
    DEFAULT_BADGE_WORKER_CACHE,
    BadgeWorkerSelection,
    BadgeWorkerCalibrator,
)
from .challenge_flow import (
    ArenaChallengeFlowError,
    ArenaChallengeRecordStore,
    contest_day_key,
    new_challenge_id,
    classify_post_challenge_page,
    result_observations_complete,
    serialise_result_observations,
)
from .badge_reference import (
    BadgeReferenceError,
    BadgeReferenceGallery,
    stable_reference_business_identity,
    stable_reference_business_candidates,
)
from .upstream_component import (
    ArenaComponentError,
    ArenaComponentManager,
    GitHubProductionSource,
    ArenaComponentResolution,
    resolve_arena_component,
)
from .customization_badge import (
    CustomizationBadgeState,
    CustomizationBadgeDecision,
    measure_customization_badge,
    duplicate_marker_visual_features,
    stable_customization_badge_presence,
    is_duplicate_marker_visual_candidate,
    customization_badge_internal_features,
)

__all__ = [
    "AdapterError",
    "ArenaComponentError",
    "ArenaComponentManager",
    "ArenaComponentResolution",
    "ArenaRuntimeConfig",
    "ArenaDecision",
    "ArenaEvaluation",
    "ArenaLineupReader",
    "ArenaPageState",
    "ArenaOwnScoreEvaluation",
    "ArenaOwnScoreService",
    "own_score_cache_prepared_for_current_task",
    "prepare_own_score_cache",
    "reset_prepared_own_score_cache",
    "ArenaCatalogError",
    "ArenaChallengeFlowError",
    "ArenaChallengeRecordStore",
    "ArenaEntityCatalog",
    "ArenaReaderBackend",
    "ArenaReaderError",
    "BadgeReferenceError",
    "BadgeReferenceGallery",
    "stable_reference_business_candidates",
    "stable_reference_business_identity",
    "BadgeWorkerCalibrator",
    "BadgeWorkerSelection",
    "ClickedSkillCard",
    "ArenaWinRateService",
    "ContestSeasonDefinition",
    "ContestStageCatalog",
    "ContestStageDefinition",
    "CustomizationObservation",
    "CustomizationEvidenceInventoryEntry",
    "GenericCostPrediction",
    "GenericCostReferenceError",
    "GenericCostReferenceGallery",
    "GitHubProductionSource",
    "CustomizationBadgeDecision",
    "CustomizationBadgeState",
    "MemberSlotMetrics",
    "MemberObservation",
    "MemberObservationScope",
    "SkillCardSlotState",
    "MemberSlotState",
    "OpponentEstimate",
    "OwnScoreBatch",
    "DEFAULT_OWN_SCORE_CACHE",
    "DEFAULT_OWN_SCORE_SUMMARY",
    "DEFAULT_BADGE_WORKER_CACHE",
    "OwnScoreCacheError",
    "OwnScoreResimulationRequired",
    "OwnScoreCacheStore",
    "StageEstimate",
    "TeamTarget",
    "SnapshotValidationError",
    "StageCatalogError",
    "SubprocessArenaAdapter",
    "classify_member_slot",
    "classify_post_challenge_page",
    "contest_day_key",
    "classify_arena_page",
    "arena_page_allows_team_entry",
    "canonical_skill_card_rows",
    "canonical_scrolled_secondary_skill_card_row",
    "expected_scrolled_secondary_skill_card_row",
    "P_ITEM_SCREEN_SLOT_TO_ENGINE_SLOT",
    "excluded_duplicate_card_flags",
    "infer_parameter_label_boxes",
    "p_item_screen_order_to_engine_order",
    "p_item_screen_slot_to_engine_slot",
    "resolve_excluded_duplicate_card_flags",
    "resolve_arena_component",
    "result_observations_complete",
    "stable_excluded_duplicate_card_flags",
    "customization_badge_internal_features",
    "measure_customization_badge",
    "new_challenge_id",
    "stable_customization_badge_presence",
    "stable_generic_cost_value",
    "fixed_member_slot_boxes",
    "duplicate_marker_visual_features",
    "is_duplicate_marker_visual_candidate",
    "team_stage_total_anchors",
    "select_first_qualified",
    "serialise_result_observations",
    "stage_member_cap",
    "validate_snapshot",
    "validate_own_snapshot",
    "validate_conservative_cost_fallback",
]
